"""V0001 - khởi tạo schema: users, scrape_jobs, job_queries,
places, place_keywords, job_places, worker_status.

Revision ID: e944b522e819
Revises: 
Create Date: 2026-09-23 09:16:49.792274
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'V0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pg_trgm cho phép ILIKE '%...%' trên cột search_text (tên + địa chỉ đã bỏ dấu)
    # vẫn dùng được chỉ mục. Không có nó thì ô tìm kiếm sẽ quét toàn bảng.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('cid', sa.String(length=32), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_raw', sa.String(length=64), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('phone_national', sa.String(length=32), nullable=True),
    sa.Column('phone_valid', sa.Boolean(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('latest_review_days', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=24), nullable=False),
    sa.Column('hours_summary', sa.String(length=160), nullable=True),
    sa.Column('has_hours', sa.Boolean(), nullable=False),
    sa.Column('website_status', sa.String(length=16), nullable=False),
    sa.Column('website_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liveness_score', sa.Integer(), nullable=False),
    sa.Column('liveness_label', sa.String(length=8), nullable=False),
    sa.Column('liveness_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detail_scraped', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_business_status'), 'places', ['business_status'], unique=False)
    op.create_index(op.f('ix_places_feature_id'), 'places', ['feature_id'], unique=True)
    op.create_index('ix_places_liveness', 'places', ['liveness_label'], unique=False)
    op.create_index('ix_places_phone_e164', 'places', ['phone_e164'], unique=False)
    op.create_index('ix_places_scraped_at', 'places', ['scraped_at'], unique=False)
    op.create_index('ix_places_status', 'places', ['status'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('done_queries', sa.Integer(), nullable=False),
    sa.Column('total_places', sa.Integer(), nullable=False),
    sa.Column('done_places', sa.Integer(), nullable=False),
    sa.Column('failed_places', sa.Integer(), nullable=False),
    sa.Column('new_places', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('worker_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_job_id', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.String(length=16), nullable=False),
    sa.Column('pace_seconds', sa.Float(), nullable=False),
    sa.Column('blocked_today', sa.Integer(), nullable=False),
    sa.Column('blocked_day', sa.String(length=10), nullable=True),
    sa.Column('pages_last_hour', sa.Integer(), nullable=False),
    sa.Column('night_rest', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'place_id', name='uq_job_places')
    )
    op.create_index(op.f('ix_job_places_job_id'), 'job_places', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_places_place_id'), 'job_places', ['place_id'], unique=False)
    op.create_table('job_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('results_found', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'query', name='uq_job_queries_job_query')
    )
    op.create_index(op.f('ix_job_queries_job_id'), 'job_queries', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_queries_status'), 'job_queries', ['status'], unique=False)
    op.create_table('place_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'keyword', name='uq_place_keywords')
    )
    op.create_index(op.f('ix_place_keywords_keyword'), 'place_keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_place_keywords_place_id'), 'place_keywords', ['place_id'], unique=False)
    # ### end Alembic commands ###


    op.execute(
        "CREATE INDEX ix_places_search_text_trgm ON places USING gin (search_text gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_places_search_text_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_keywords_place_id'), table_name='place_keywords')
    op.drop_index(op.f('ix_place_keywords_keyword'), table_name='place_keywords')
    op.drop_table('place_keywords')
    op.drop_index(op.f('ix_job_queries_status'), table_name='job_queries')
    op.drop_index(op.f('ix_job_queries_job_id'), table_name='job_queries')
    op.drop_table('job_queries')
    op.drop_index(op.f('ix_job_places_place_id'), table_name='job_places')
    op.drop_index(op.f('ix_job_places_job_id'), table_name='job_places')
    op.drop_table('job_places')
    op.drop_table('worker_status')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index('ix_places_status', table_name='places')
    op.drop_index('ix_places_scraped_at', table_name='places')
    op.drop_index('ix_places_phone_e164', table_name='places')
    op.drop_index('ix_places_liveness', table_name='places')
    op.drop_index(op.f('ix_places_feature_id'), table_name='places')
    op.drop_index(op.f('ix_places_business_status'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
